# Generated by Django 5.0.2 on 2024-02-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("age", models.IntegerField()),
                ("address", models.CharField(max_length=2000)),
                ("phone_no", models.CharField(max_length=8)),
            ],
        ),
    ]
